platform :ios,'7.0'
pod 'JSONKit', '~> 1.5pre'
pod 'Reachability', '~> 3.1.1'
pod 'MKNetworkKit', '~> 0.87'
pod 'SDWebImage', '~> 3.5'
pod 'SVProgressHUD', '~> 1.0'
pod 'FMDB', '~> 2.1'
pod 'SVPullToRefresh', '~> 0.4.1'
pod 'Masonry', '~> 0.3.0'